name: wiki_edited

on:
  gollum

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: open PR
      run: echo "TODO"
    
    - name: revert changes to wiki
      run: |
        git remote add wiki https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/havogt/wiki_template.wiki.git
        git push wiki master --force
