name: wiki_edited

on:
  gollum

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: debug
      run: git remove -vv
    
    - name: debug2
      run: |
        echo ${{ GITHUB_SHA }}
        echo ${{ GITHUB_REF }}
