name: wiki_edited

on:
  gollum

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup repo
      run: |
        git remote add wiki https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/havogt/wiki_template.wiki.git
        git fetch wiki

    - name: push branch
      run: |
        git checkout ${GITHUB_SHA}
        export branch_name=$(mktemp -u pr_XXXXXXXXXXXXXX)
        echo "::set-env name=PULL_REQUEST_FROM_BRANCH::${branch_name}"
        git checkout -b $branch_name
        git push origin $branch_name
    
    - name: pull-request-action
      uses: vsoch/pull-request-action@1.0.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_BRANCH: "master"
            
#     - uses: repo-sync/pull-request@v2
#       with:
#         source_branch: "${{ env.branch_name }}"
#         destination_branch: "master"
#         pr_title: "From wiki edit ${{ env.branch_name }}"
#         pr_body: "Opened from wiki edit"
#         pr_draft: false
#         pr_allow_empty: true
#         github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: revert changes to wiki
      run: |
        echo $branch_name
        git push wiki master --force
